language: python

sudo: false

cache:
  directories:
  - "$HOME/.cache/pip"

matrix:
  fast_finish: true
  include:
  - python: "3.5"
    env: TOXENV=lint
  - python: "3.5"
    env: TOXENV=packagecheck

  - python: "3.6"
    env: TOXENV=py36-django21
  - python: "3.5"
    env: TOXENV=py35-django21

  - python: "3.6"
    env: TOXENV=py36-django20
  - python: "3.5"
    env: TOXENV=py35-django20
  - python: "3.4"
    env: TOXENV=py34-django20

  - python: "3.6"
    env: TOXENV=py36-django111
  - python: "3.5"
    env: TOXENV=py35-django111
  - python: "3.4"
    env: TOXENV=py34-django111

  - python: "3.7"
    env: TOXENV=py37-djangomaster
  - python: "3.6"
    env: TOXENV=py36-djangomaster

  allow_failures:
  - env: TOXENV=py37-djangomaster
  - env: TOXENV=py36-djangomaster

install:
- pip install tox

script:
- tox

after_success:
- pip install codecov
- codecov -e TOXENV

notifications:
  email:
    on_success: never
    on_failure: always
